CREATE DATABASE IF NOT EXISTS gallery_vinn CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gallery_vinn;

CREATE TABLE IF NOT EXISTS user (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) UNIQUE NOT NULL,
  Email VARCHAR(100) UNIQUE,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS foto (
  FotoID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  JudulFoto VARCHAR(255),
  DeskripsiFoto TEXT,
  LokasiFile VARCHAR(255),
  TanggalUpload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likefoto (
  LikeID INT AUTO_INCREMENT PRIMARY KEY,
  FotoID INT NOT NULL,
  UserID INT NOT NULL,
  TanggalLike TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (FotoID) REFERENCES foto(FotoID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS komentarfoto (
  KomentarID INT AUTO_INCREMENT PRIMARY KEY,
  FotoID INT NOT NULL,
  UserID INT NOT NULL,
  IsiKomentar TEXT,
  TanggalKomentar TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (FotoID) REFERENCES foto(FotoID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);
